# Phase 1 - Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [16]:
sm = pd.read_csv("../data/raw/Social_media_impact_on_life.csv")
teen = pd.read_csv("../data/raw/Teen_Mental_Health_Dataset.csv")

In [28]:
sm.head()

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,overall_impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative

In [29]:
teen.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [17]:
print(sm.shape, teen.shape)

(1705, 11) (1200, 13)

In [20]:
sm.info()
print('=' * 50)
teen.info()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   str
 3   Academic_Level                1705 non-null   str
 4   Country                       1705 non-null   str
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   str
 7   Affects_Academic_Performance  1705 non-null   str
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 212.3 KB
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 140.4 KB

In [ ]:
# Checking Null Values
print(sm.isnull().sum())
print('-*-' * 20)
print(teen.isnull().sum())

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
dtype: int64

In [25]:
# Checking Duplicate Values
print(sm.duplicated().sum())
print(teen.duplicated().sum())
# If duplicate present
# sm.drop_duplicates(inplace=True)
# teen.drop_duplicates(inplace=True)

0
0

In [27]:
# Fixing Column Names
sm.columns = sm.columns.str.strip().str.lower().str.replace(" ", "_")
teen.columns = teen.columns.str.strip().str.lower().str.replace(" ", "_")

In [ ]:
# Fixing Datatypes
sm['age'] = sm['age'].astype(int)
sm['avg_daily_usage_hours'] = sm['avg_daily_usage_hours'].astype(int)

In [32]:
# Fixing Datatypes
teen['age'] = teen['age'].astype(int)
teen['daily_social_media_hours'] = teen['daily_social_media_hours'].astype(int)

In [34]:
# Fill Numeric nulls with median
# Why Median not mean?
# Median is robust to outliers
# Ex:
# values = [10, 20, 30, 1000]
# mean = 265
# median = 25    # better

In [38]:
# Numeric columns
for col in sm.select_dtypes('number').columns:
    sm[col] = sm[col].fillna(sm[col].median())

for col in teen.select_dtypes('number').columns:
    teen[col] = teen[col].fillna(teen[col].median())

In [42]:
# Categorical columns
for col in sm.select_dtypes(include=['object', 'string']):
    sm[col] = sm[col].fillna(sm[col].mode()[0])

for col in teen.select_dtypes(include=['object', 'string']):
    teen[col] = teen[col].fillna(teen[col].mode()[0])

# for col in sm.select_dtypes(include='object'):
#     sm[col] = sm[col].fillna(sm[col].mode()[0])

# for col in teen.select_dtypes(include='object'):
#     teen[col] = teen[col].fillna(teen[col].mode()[0])

```json
| dtype    | meaning                 |
| -------- | ----------------------- |
| `object` | old string / mixed data |
| `string` | new pandas string type  |

```

## Encode Categorical Columns

In [43]:
sm.columns

Index(['student_id', 'age', 'gender', 'academic_level', 'country',
       'avg_daily_usage_hours', 'most_used_platform',
       'affects_academic_performance', 'sleep_hours_per_night',
       'mental_health_score', 'overall_impact'],
      dtype='str')

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

cat_cols_sm = ['gender', 'academic_level', 'country', 'most_used_platform',
            'affects_academic_performance', 'overall_impact']
for col in cat_cols_sm:
    sm[col] = le.fit_transform(sm[col])

In [45]:
teen.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level',
       'anxiety_level', 'addiction_level', 'depression_label'],
      dtype='str')

In [46]:
cat_cols_teen = ['gender', 'platform_usage', 'social_interaction_level']
for col in cat_cols_teen:
    teen[col] = le.fit_transform(teen[col])

In [47]:
sm.head()

,student_id,age,gender,academic_level,country,avg_daily_usage_hours,most_used_platform,affects_academic_performance,sleep_hours_per_night,mental_health_score,overall_impact
0,232,21,1,2,73,4,0,0,6.7,6.8,1
1,564,23,0,2,73,1,4,0,8.6,7.6,2
2,788,22,1,0,18,4,1,0,6.7,7.0,1
3,686,18,1,2,73,7,5,1,5.4,5.3,0
4,608,24,0,1,73,7,0,1,5.0,4.4,0

In [48]:
teen.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,1,7,1,7.4,2.9,3.01,1.5,1,2,2,1,0
1,19,0,1,2,8.0,2.9,3.22,0.8,0,8,1,10,0
2,17,0,1,1,7.6,0.5,3.92,0.0,0,2,4,2,0
3,15,1,7,2,6.9,1.6,3.48,0.8,2,1,7,9,0
4,15,0,4,0,4.9,3.0,2.37,1.4,2,3,5,2,0

In [49]:
# Check Outliers (IQR)
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    return df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

sm = remove_outliers(sm, 'avg_daily_usage_hours')
teen = remove_outliers(teen, 'daily_social_media_hours')

print(sm.shape, teen.shape)

(1705, 11) (1200, 13)

In [50]:
sm.to_csv("../data/cleaned/social_media_cleaned.csv", index=False)
teen.to_csv("../data/cleaned/teen_mental_health_cleaned.csv", index=False)

print("Cleaned data saved!")

Cleaned data saved!